/serial_parser:
  ros__parameters:
    port_name: "/dev/ttyACM1"
    baud_rate: 115200

/localisation_engine_node:
  ros__parameters:
    # anchor_2, anchor_3, anchor_4, anchor_5
    anchor_positions_param: [0.0, 0.0, 1.225, 0.0, 8.089, 1.225, -5.681, 7.818, 1.225, -5.789, 0.0, 1.225]
    robot_process_noise_stdev: 0.2
    measurement_noise_stdev: 0.2

/mqtt_publihser_node:
  ros__parameters:
    mqtt_host: "10.81.101.228"



/mqtt_subscriber_node:
  ros__parameters:
    mqtt_host: "localhost"

/marker_generator_node:
  ros__parameters:
    marker_green: 0.0
    marker_red: 0.0
    marker_blue: 1.0

    